/**
 * Platform independent logic for revealing locations in the file manager of the operating system.
 * This module must not import anything, because it is shared between the web-app (NW.js renderer) and the Electron main process.
 *
 * Security considerations:
 * - The renderer is a (remote) web origin, so all input is validated as untrusted.
 * - Only path segments without separators/special names are accepted (no traversal outside of the root).
 * - Directories are opened, files are only revealed (selected in their folder) and **never** launched,
 *   since opening a file with its default handler may execute it (e.g., an `.exe`/`.lnk` on Windows).
 */

export type FileStat = {
    isDirectory(): boolean;
};

export type PathOperations = {
    join(...segments: string[]): string;
    isAbsolute(path: string): boolean;
    basename(path: string): string;
    /**
     * @returns `null` when the path does not exist, throws on any other error (e.g., permission denied)
     */
    stat(path: string): Promise<FileStat | null>;
};

export type RevealOperations = {
    openDirectory(path: string): Promise<void>;
    revealFile(path: string): Promise<void> | void;
};

export type NearestLocation = {
    readonly Path: string;
    readonly IsDirectory: boolean;
    /** `true` when the requested location itself exists (not just a parent) */
    readonly Exact: boolean;
};

const maxEntriesToVerify = 64;

/**
 * Check if the given value is a single, plain file/directory name.
 * Rejects separators, `.`/`..`, control characters and `:` (drive-relative paths and NTFS alternate data streams).
 * @remarks All names generated by HakuNeko are sanitized and therefore never contain any of these characters.
 */
export function IsValidSegment(segment: unknown): segment is string {
    return typeof segment === 'string'
        && segment.length > 0
        && segment.length <= 255
        && segment !== '.'
        && segment !== '..'
        && !/[/\\:\p{Cc}]/u.test(segment);
}

function AssertSafeLocation(operations: PathOperations, root: unknown, segments: unknown): asserts segments is string[] {
    if(typeof root !== 'string' || root.length === 0 || !operations.isAbsolute(root)) {
        throw new Error('The root directory must be an absolute path!');
    }
    if(!Array.isArray(segments) || !segments.every(IsValidSegment)) {
        throw new Error('The location contains invalid path segments!');
    }
}

/**
 * Find the deepest existing entry of `root/segments...`, walking up to the {@link root} itself.
 * @returns `null` when not even the {@link root} exists (e.g., disconnected drive)
 */
export async function FindNearestExisting(operations: PathOperations, root: string, segments: string[]): Promise<NearestLocation | null> {
    AssertSafeLocation(operations, root, segments);
    for(let depth = segments.length; depth >= 0; depth--) {
        const path = operations.join(root, ...segments.slice(0, depth));
        const stat = await operations.stat(path);
        if(stat) {
            return { Path: path, IsDirectory: stat.isDirectory(), Exact: depth === segments.length };
        }
    }
    return null;
}

/**
 * Verify that the absolute {@link directory} corresponds to the directory handle with the given {@link name},
 * by checking the directory name and the existence of some {@link entries} which are visible through the handle.
 */
export async function VerifyDirectory(operations: PathOperations, directory: unknown, name: unknown, entries: unknown): Promise<boolean> {
    if(typeof directory !== 'string' || directory.length === 0 || !operations.isAbsolute(directory)) {
        return false;
    }
    if(!Array.isArray(entries) || entries.length > maxEntriesToVerify || !entries.every(IsValidSegment)) {
        return false;
    }
    try {
        const stat = await operations.stat(directory);
        if(!stat?.isDirectory()) {
            return false;
        }
        // NOTE: The base name of a drive root (e.g., `D:\`) is empty and cannot be compared
        const basename = operations.basename(directory);
        if(basename && typeof name === 'string' && name && basename.normalize('NFC') !== name.normalize('NFC')) {
            return false;
        }
        for(const entry of entries) {
            if(!await operations.stat(operations.join(directory, entry))) {
                return false;
            }
        }
        return true;
    } catch {
        return false;
    }
}

/**
 * Open the deepest existing directory of `root/segments...` in the file manager,
 * or reveal it in its folder when the deepest existing entry is a file (e.g., `.cbz`).
 * @returns The path that was opened/revealed, or `null` when the {@link root} does not exist
 */
export async function RevealPath(operations: PathOperations, reveal: RevealOperations, root: string, segments: string[]): Promise<string | null> {
    const nearest = await FindNearestExisting(operations, root, segments);
    if(!nearest) {
        return null;
    }
    if(nearest.IsDirectory) {
        await reveal.openDirectory(nearest.Path);
    } else {
        await reveal.revealFile(nearest.Path);
    }
    return nearest.Path;
}

type NodeFileSystem = {
    stat(path: string): Promise<FileStat>;
};

type NodePath = {
    join(...segments: string[]): string;
    isAbsolute(path: string): boolean;
    basename(path: string): string;
};

/**
 * Create the {@link PathOperations} based on the NodeJS modules `fs/promises` and `path`.
 */
export function CreateNodePathOperations(fs: NodeFileSystem, path: NodePath): PathOperations {
    return {
        join: (...segments: string[]) => path.join(...segments),
        isAbsolute: (location: string) => path.isAbsolute(location),
        basename: (location: string) => path.basename(location),
        stat: async (location: string) => {
            try {
                return await fs.stat(location);
            } catch(error) {
                const code = (error as { code?: string })?.code;
                if(code === 'ENOENT' || code === 'ENOTDIR') {
                    return null;
                }
                throw error;
            }
        },
    };
}
